query anomalies($beginTime: DateTime!) {
  objects: workloadAnomalies(beginTime: $beginTime) {
    nodes {
      workloadName
      objectType
      severity
      createdFileCount
      deletedFileCount
      modifiedFileCount
      suspiciousFileCount
      encryption
      anomalousSnapshotDate
      anomalyInfo {
        strainAnalysisInfo {
          strainId
        }
      }
    }
  }
}