mutation closeManagedVolume($id: String!){
  endManagedVolumeSnapshot(input: {id: $id}) {
    asyncRequestStatus {
      id
      status
      startTime
      endTime
      error {
        message
      }
    }
  }
}
