query events($since: DateTime) {
  objects: activitySeriesConnection(filters: {
  	lastActivityStatus: [FAILURE, SUCCESS, CANCELED]
  	lastUpdatedTimeGt: $since
    #severity: [SEVERITY_INFO,SEVERITY_WARNING,SEVERITY_CRITICAL]
    #lastActivityType: BACKUP
    #objectType: VMWARE_VM
  }) {
    nodes {
      fid
      id
      startTime
      lastUpdated
      lastActivityType
      lastActivityStatus
      severity
      objectId
      objectName
      objectType
      clusterUuid
      clusterName
      lastEventAddedAt
      lastVerifiedAt
      isPolarisEventSeries
      effectiveThroughput
      dataTransferred
      logicalSize
      organizations {
        name
      }
      failureReason
      causeErrorMessage
      causeErrorCode
      causeErrorReason
      causeErrorRemedy
      activityConnection(first: 1) {
        nodes {
          time
          errorInfo
          message
        }
      }
    }
  }
}
