query getAzureVmByName($name: String!) {
  objects: azureNativeVirtualMachines(virtualMachineFilters: {
    nameSubstringFilter: {
      nameSubstring: $name
    }
  }) {
    edges {
      node {
        vmName
        id
      }
    }
  }
}