query getAzureStorageAccounts {
  objects: azureNativeRoot {
    storageAccounts: objectTypeDescendantConnection(objectTypeFilter: AZURE_STORAGE_ACCOUNT) {
      nodes {
        name
        id
        region
        effectiveSlaDomain {
          name
          id
        }
      }
    }
  }
}
