query getMssqlJobStatus($id: String! $clusterUuid: String!) {
  mssqlJobStatus(input: {
  	id: $id
    clusterUuid: $clusterUuid
  }) {
    startTime
    endTime
    error {
      message
    }
    progress
    status
  }
}
