query GetMSSQLInstance($hostname: [String!]) {
  objects: mssqlTopLevelDescendants(filter: [{field: NAME, texts: $hostname}, {field: IS_RELIC, texts: "false"}, {field: IS_ARCHIVED, texts: "false"}, {field: IS_REPLICATED, texts: "false"}]) {
    nodes {
      id
      name
      numWorkloadDescendants
      ... on PhysicalHost {
        id
        name
        cbtStatus
        physicalChildConnection {
          nodes {
            ... on MssqlInstance {
              id
              name
              slaAssignment
              effectiveSlaDomain {
                name
                id
                version
              }
            }
          }
        }
      }
    }
  }
}
