mutation openManagedVolume($id: String!){
  beginManagedVolumeSnapshot(input: {id: $id config: {isAsync: true}}) {
    snapshotId
    asyncRequestStatus {
      id
      status
      startTime
      endTime
      error {
        message
      }
    }
  }
}
