query slaDomains {
  objects: slaDomains {
    nodes {
      name
      id
      ... on GlobalSlaReply {
        localRetentionLimit {
          duration
          unit
        }
        baseFrequency {
          duration
          unit
        }
      }
    }
  }
}