mutation takeMssqlOnDemandBackup($id: String! $slaId: String) {
  createOnDemandMssqlBackup(
    input: {
      id: $id 
      config: {
        baseOnDemandSnapshotConfig: {
          slaId: $slaId
        }
      }
    }) {
    id
  }
}
