---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    query_file: ""
    query_variables: ""
  vars_files:
    - /MY/VAULT/LOCATION

  tasks:
    - name: Connect RSC
      uri:
        url: "{{ rsc_instance.uri }}/api/client_token"
        method: POST
        body_format: json
        body:
          client_id: "{{ rsc_instance.client_id }}"
          client_secret: "{{ rsc_instance.client_secret }}"
      register: rsc

    - name: RSC GraphQL Query
      uri:
        url: "{{ rsc_instance.uri }}/api/graphql"
        method: POST
        headers:
          content-type: "application/json"
          authorization: "Bearer {{ rsc.json.access_token }}"
        body_format: json
        body: 
          query: '{{ lookup("file", "{{ query_file }}") }}'
          variables: "{{ query_variables }}"
      register: query_result
    
    - name: Debug Output
      debug:
        var: query_result.json.data

    - name: Disconnect RSC
      uri:
        url: "{{ rsc_instance.uri}}/api/session"
        method: DELETE
        headers:
          authorization: "{{ rsc.json.access_token }}"
        status_code: [204]
 